openapi: 3.0.0
info:
  title: Онлайн магазин
  description: API для управления товарами в онлайн магазине
  version: 1.0.1
servers:
  - url: "http://localhost:3000/"
    description: Локальный сервер 3000
  - url: "http://localhost:5000/"
    description: Локальный сервер 5000
  - url: "http://localhost:8080/"
    description: Локальный сервер 8080
paths:
  /products:
    get:
      summary: Получение товаров
      tags:
        - Products
      operationId: getAllProducts
      responses:
        "200":
          description: Товары получены успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        "401":
          description: Пользователь не авторизован
        "403":
          description: Действие запрещено
        "500":
          description: Ошибка сервера
        "default":
          description: Что-то пошло не так
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Создание товара
      tags:
        - Products
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"   
      responses:
        "201":
          description: Товар создан успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400": 
          description: Некорректные данные
        "401":
          description: Пользователь не авторизован
        "403":
          description: Действие запрещено
        "500":
          description: Ошибка сервера
        "default":
          description: Что-то пошло не так
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                  
              
  /products/{product_id}:
    get:
      summary: Получение товара по его идентификатору
      tags:
        - Products
      operationId: getProductById
      parameters:
        - name: product_id
          in: path
          required: true
          description: Идентификатор товара
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: Товар получен успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400": 
          description: Некорректный идентификатор
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "403":
          description: Действие запрещено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "404":
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "default":
          description: Что-то пошло не так
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
                
    put:
      summary: Полное обновление товара по его идентификатору
      tags:
        - Products
      operationId: updateProductById
      parameters:
        - name: product_id
          in: path
          required: true
          description: Идентификатор товара
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Товар обновлён успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400": 
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "403":
          description: Действие запрещено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "404":
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "default":
          description: Что-то пошло не так
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"                
  
    delete: 
      summary: Удаление товара по его идентификатору
      tags:
        - Products
      operationId: deleteProductById
      parameters:
        - name: product_id
          in: path
          required: true
          description: Идентификатор товара
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "204":
          description: Успешное удаление товара
        "400": 
          description: Некорректный идентификатор
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "401":
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "403":
          description: Действие запрещено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "404":
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"  
        "default":
          description: Что-то пошло не так
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"        

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - cost
      properties:
        product_id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Автомобиль
          minLength: 1
          maxLength : 15
        cost:
          type: number
          example: 50
          minimum: 1
    ProductInput:
      type: object
      required:
        - name
        - cost
      properties:
        name:
          type: string
          example: Автомобиль
          minLength: 1
          maxLength : 15          
        cost:
          type: number
          example: 50
          minimum: 1
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Error:
      type: object
      required:
        - code
        - message
        - timestamp        
      properties:
        code:
          type: integer
          example: 418
        message:
          type: string
          example: Я чайник
        timestamp:
          type: string
          format: date-time
          description: Время ошибки
          example: "2025-01-01T00:00:00Z"